# Generated by Django 5.1.2 on 2025-01-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='descrizione',
            field=models.TextField(default='Descrizione non disponibile'),
            preserve_default=False,
        ),
    ]
