# Generated by Django 5.1.2 on 2025-01-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_roll_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=20)),
                ('descrizione', models.TextField()),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='roll',
            name='descrizione',
        ),
    ]
