# Generated by Django 5.1.2 on 2025-01-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0003_sushi_remove_roll_descrizione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sushi',
        ),
        migrations.AddField(
            model_name='roll',
            name='descrizione',
            field=models.TextField(default='Descrizione non disponibile'),
        ),
    ]
