# Generated by Django 5.1.2 on 2025-01-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('aggiunto_il', models.DateTimeField(auto_now_add=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.roll')),
            ],
        ),
    ]
