# Generated by Django 5.1.2 on 2025-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='aggiunto_il',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale', models.FloatField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='rolls.cartitem')),
            ],
        ),
    ]
